jantar = ["didi", "ju", "cat", "sequeira"]

print(f"Caro {jantar[0]} estás convidado para jantar nos meus aposentos!")
print(f"Caro {jantar[1]} estás convidado para jantar nos meus aposentos!")
print(f"Caro {jantar[-2]} estás convidado para jantar nos meus aposentos!")
print(f"Caro {jantar[-1]} estás convidado para jantar nos meus aposentos!")
print("\n")
print(f"Afinal o gordo do {jantar[-1]} já não vem :( ")
print("\n")
del jantar[-1]
jantar.append("kumar")
print(f"Caro {jantar[0]} estás convidado para jantar nos meus aposentos!")
print(f"Caro {jantar[1]} estás convidado para jantar nos meus aposentos!")
print(f"Caro {jantar[2]} estás convidado para jantar nos meus aposentos!")
print(f"Caro {jantar[3]} estás convidado para jantar nos meus aposentos!")
print("\n")
jantar.insert(0, "dentinho")
jantar.insert(2, "vargas")
jantar.append("girao")
print(jantar)
print(" Afinal só vou poder convidar duas pessoas sorry")
popped_1 = jantar.pop(0)
print(f"Lamento {popped_1} nao vai dar !")
popped_2 = jantar.pop(0)
print(f"Lamento {popped_2} nao vai dar !")
popped_3 = jantar.pop(0)
print(f"Lamento {popped_3} nao vai dar !")
popped_4 = jantar.pop(0)
print(f"Lamento {popped_4} nao vai dar !")
popped_5 = jantar.pop(0)
print(f"Lamento {popped_5} nao vai dar !")
print("\n")
print(jantar)
print(f"{jantar[0]} e {jantar[1]} ainda estão convidados!")
numero = len(jantar)
print(f"no toal somos {numero} sem contar comigo !!")
del jantar[0]
del jantar[0]
print("\n")
print(jantar)
